name: custom_countdown
description: A customizable circular countdown timer widget.
version: 0.0.1
homepage: https://github.com/Boburbek6010/custom_countdown

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0